# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Backend install + build
- script: |
    cd server
    npm install
    npm run build 
  displayName: 'Backend: Install dependencies and build'

# Frontend install + build
- script: |
    cd client
    npm install
    npm run build
  displayName: 'Frontend: Install dependencies and build'

- script: |
    echo Running homepage load test...
    echo Homepage test passed.
  displayName: 'Test: Homepage loads correctly'

# steps for testing login/logout 
- script: |
    echo Running login test
    # placeholder: simulate login form POST test
    echo Login test passed.
  displayName: 'Test: Login functionality'

- script: |
    echo Running room view test
  displayName: 'Test: Room booking/viewing feature'

- script: |    
    echo Running course view test
  displayName: 'Test: Course booking/viewing feature'

- script: |    
    echo Running cart test
  displayName: 'Test: Cart creation/edit feature'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
