trigger:
- dev

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'   # 先用 LTS；确认平台支持再升 22.x

steps:
# 1) Node 版本
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Use Node $(nodeVersion)'

# 2) Backend: 安装 & 构建
- script: |
    set -e
    npm ci
    npm run build
  displayName: 'Backend: install & build'
  workingDirectory: server

# 3) Frontend: 安装 & 构建
- script: |
    set -e
    npm ci
    npm run build
  displayName: 'Frontend: install & build'
  workingDirectory: client
  env:
    NODE_OPTIONS: '--max-old-space-size=4096'   # 大项目打包更稳（可选）

# 4) Backend: 测试
- script: |
    set -e
    npm ci
    npm test
  displayName: 'Backend: test'
  workingDirectory: server

