# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Backend install + build
- script: |
    cd server
    npm install
    npm run build 
  displayName: 'Backend: Install dependencies and build'

# Frontend install + build
- script: |
    cd client
    npm install
    npm run build
  displayName: 'Frontend: Install dependencies and build'

# steps for testing 
- script: |
    echo Running tests
    # placeholder: run all the test files
    echo All test passed.
  displayName: 'Run Tests'

# put below into a separate yaml?? depends how you structure
# have main CD pipeline
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#     includeRootFolder: false
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactsStagingDirectory)/$(Build.BuildId).zip'
#     replaceExisting Archive: true
#   displayName: 'ZIP Project'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(Build.ArtifactsStagingDirectory)'
#     artifactName: 'drop'
#     publishLocation: 'Container'
#   displayName: 'Publish Artifact'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'AzureAppConnection'
#     appName: ''
#     package: '$(Build.ArtifactsStagingDirectory)/*.zip'
#   displayName: 'Deploy to Azure App Services'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
